# Generated by Django 4.2 on 2023-06-02 18:38

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to=services.uploader.Uploader.upload_profile_photo),
        ),
    ]
