# Generated by Django 4.2 on 2023-06-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userbase_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbase',
            old_name='user_name',
            new_name='username',
        ),
    ]
