# Generated by Django 4.2 on 2023-06-05 15:01

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_user_name_userbase_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='profile_photo',
            field=models.ImageField(blank=True, default='../static/assets/images/default.png', upload_to=services.uploader.Uploader.upload_profile_photo),
        ),
    ]
