# Generated by Django 4.2 on 2023-05-30 17:00

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=services.uploader.Uploader.upload_image_blog),
        ),
    ]
