# Generated by Django 4.2 on 2023-05-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_title_alter_blogimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogimage',
            options={'ordering': ('-created_at',), 'verbose_name': 'BlogImage', 'verbose_name_plural': 'BlogImages'},
        ),
    ]
