# Generated by Django 4.2 on 2023-06-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_blogimage_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
