# Generated by Django 4.2 on 2023-06-05 15:59

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_alter_blog_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(default='../static/assets/images/default-blog.png', max_length=500, upload_to=services.uploader.Uploader.upload_image_blog),
        ),
    ]
