# Generated by Django 4.2 on 2023-06-05 16:17

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_blogimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=services.uploader.Uploader.upload_image_blog),
        ),
    ]
